---
- name: Install Pip
  become: true
  apt:
    name: python-pip
    update_cache: yes

- name: Install prerequisites
  become: true
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    update_cache: yes

- name: Add Docker GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Add Docker APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker
  become: true
  apt:
    name: docker-ce
    update_cache: true
- name: Install docker-py
  become: true
  pip:
    name: "docker-py"
